project_name = "My first song"
bpm = 127.0

[[tracks]]
name = "kick"
mute = false
steps = [95.0, 0.0, 0.0, 0.0, 95.0, 0.0, 0.0, 0.0, 95.0, 0.0, 0.0, 0.0, 95.0, 0.0, 0.0, 0.0]
sample_path = "./example_drums/SharpK.wav"
position = 0.0
target_volume = 0.7480315
track_volume = 1.0
is_playing = false

[[tracks]]
name = "hat"
mute = false
steps = [0.0, 0.0, 95.0, 0.0, 0.0, 0.0, 95.0, 0.0, 0.0, 0.0, 95.0, 0.0, 0.0, 0.0, 95.0, 0.0]
sample_path = "./example_drums/PopOHH.wav"
position = 0.0
target_volume = 0.7480315
track_volume = 1.0
is_playing = false

[[tracks]]
name = "snare"
mute = false
steps = [0.0, 95.0, 0.0, 0.0, 95.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 95.0, 0.0, 0.0, 95.0]
sample_path = "./example_drums/AttackS.wav"
position = 0.0
target_volume = 0.7480315
track_volume = 1.0
is_playing = false
