name = "New Project"
bpm = 120.0
master_volume = 1.0

[[audio_blocks]]
id = 0
track = 0
start_step = 0
length = 1

[audio_blocks.block_type]
kind = "Mixing"

[[audio_blocks]]
id = 1
track = 0
start_step = 0
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 0

[[audio_blocks]]
id = 3
track = 0
start_step = 8
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 0

[[audio_blocks]]
id = 5
track = 0
start_step = 4
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 0

[[audio_blocks]]
id = 6
track = 1
start_step = 0
length = 16

[audio_blocks.block_type]
kind = "Pattern"
id = 0

[[audio_blocks]]
id = 7
track = 0
start_step = 12
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 0

[[audio_blocks]]
id = 8
track = 2
start_step = 2
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 1

[[audio_blocks]]
id = 10
track = 2
start_step = 10
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 1

[[audio_blocks]]
id = 11
track = 2
start_step = 14
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 1

[[audio_blocks]]
id = 14
track = 3
start_step = 8
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 2

[[audio_blocks]]
id = 15
track = 4
start_step = 3
length = 1

[audio_blocks.block_type]
kind = "Mixing"

[[audio_blocks]]
id = 16
track = 2
start_step = 6
length = 1

[audio_blocks.block_type]
kind = "Sample"
id = 1

[[tracks]]
id = 0
name = "bounce-kick-02.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/kicks/bounce-kick-02.wav"
is_muted = false
channels = 1
target_volume = 1.0
track_volume = 1.0
root_note = 60

[[tracks]]
id = 1
name = "hi-hat-closed-01.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/hi-hats/hi-hat-closed-01.wav"
is_muted = false
channels = 1
target_volume = 1.0
track_volume = 1.0
root_note = 60

[[tracks]]
id = 2
name = "clap-01.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/claps/clap-01.wav"
is_muted = false
channels = 1
target_volume = 1.0
track_volume = 1.0
root_note = 60

[[patterns]]
id = 0
name = "Pattern 1"
sequences = []
