name = "New Project"
bpm = 120.0
master_volume = 1.0

[[audio_blocks]]
id = 0
track_id = 2
start_step = 4
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Mixing"

[[audio_blocks]]
id = 10
track_id = 0
start_step = 0
length = 2
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 11
track_id = 0
start_step = 2
length = 2
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 12
track_id = 0
start_step = 4
length = 2
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 13
track_id = 0
start_step = 6
length = 2
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 14
track_id = 0
start_step = 8
length = 2
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 15
track_id = 0
start_step = 10
length = 2
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 16
track_id = 0
start_step = 12
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 17
track_id = 0
start_step = 13
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 18
track_id = 0
start_step = 14
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 19
track_id = 0
start_step = 15
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 4

[[audio_blocks]]
id = 20
track_id = 4
start_step = 15
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Mixing"

[[audio_blocks]]
id = 21
track_id = 3
start_step = 13
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Mixing"

[[audio_blocks]]
id = 22
track_id = 3
start_step = 8
length = 1
is_muted = false

[audio_blocks.block_type]
kind = "Mixing"

[[audio_blocks]]
id = 23
track_id = 7
start_step = 0
length = 17
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 5

[[audio_blocks]]
id = 24
track_id = 6
start_step = 0
length = 2
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 6

[[audio_blocks]]
id = 25
track_id = 8
start_step = 0
length = 17
is_muted = false

[audio_blocks.block_type]
kind = "Sample"
id = 7

[[tracks]]
id = 0
name = "bounce-snare-01.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/snares/bounce-snare-01.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[tracks]]
id = 1
name = "cp.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/claps/cp.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[tracks]]
id = 2
name = "open-hat-01.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/open-hats/open-hat-01.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[tracks]]
id = 3
name = "vintage-snare-01.wav"
path = "./assets/free-drum-samples/drum-samples/03-soulful-vintage/snares/vintage-snare-01.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[tracks]]
id = 4
name = "hi-hat-closed-01.wav"
path = "./assets/free-drum-samples/drum-samples/03-soulful-vintage/hi-hats/hi-hat-closed-01.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[tracks]]
id = 5
name = "clap-01.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/claps/clap-01.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[tracks]]
id = 6
name = "hi-hat-closed-01.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/hi-hats/hi-hat-closed-01.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[tracks]]
id = 7
name = "fx-cymbal.wav"
path = "./assets/free-drum-samples/drum-samples/02-bounce/fx/fx-cymbal.wav"
is_muted = false
channels = 1
track_volume = 1.0
root_note = 60

[[patterns]]
id = 0
name = "Pattern 1 so long"
sequences = []
