[book]
title = "glacier"
authors = ["Remy"]
language = "en"
description = "Architecture and internals of the Glacier DAW"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
